FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["AgendaAPI/AgendaAPI.csproj", "AgendaAPI/"]
RUN dotnet restore "AgendaAPI/AgendaAPI.csproj"
COPY . .
WORKDIR "/src/AgendaAPI"
RUN dotnet build "AgendaAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AgendaAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AgendaAPI.dll"]